# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BLGkhPfEemiSC6oTM_HeNq5ST_heOhAk
"""

import streamlit as st
import numpy as np
import tensorflow as tf
from tensorflow.keras.models import load_model
from PIL import Image

# Load decoder model
@st.cache_resource
def load_decoder():
    return load_model("decoder.h5")

decoder = load_decoder()

# Set up UI
st.title("MNIST Digit Generator (CVAE)")
digit = st.selectbox("Choose a digit (0–9)", list(range(10)))

# Generate 5 images
if st.button("Generate Images"):
    latent_dim = decoder.input_shape[0][1]
    num_images = 5
    z = np.random.normal(size=(num_images, latent_dim))
    labels = np.zeros((num_images, 10))
    labels[:, digit] = 1

    generated = decoder.predict([z, labels])
    generated = generated.squeeze()  # shape: (5, 28, 28)

    st.subheader(f"Generated images for digit: {digit}")
    cols = st.columns(5)
    for i in range(num_images):
        img = (generated[i] * 255).astype(np.uint8)
        im = Image.fromarray(img)
        cols[i].image(im, use_column_width=True)